---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: '11.4.0'

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

suites:
- name: source_26_10
  run_list: ["recipe[redis]"]
  attributes: 
    redis:
      source:
        version: 2.6.10
